import pygame
import random


class Enemy:
    def __init__(self, name):
        self.name = name


        if name == "Slime":
            self.strength = 5
            self.agility = 3
            self.HP = (3,3)
            self.sleep_resist = 0 / 16.0
            self.stopspell_resist = 15/16.0
            self.hurt_resist = 0 / 16.0
            self.dodge = 1/64.0
            self.E = 1
            self.G = (1, 1)
            self.run_resist = 0.25
            self.pattern = [("Attack", 1)]
            self.image = pygame.image.load("images/enemies/slime.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/slime_shadow.png").convert()
        elif name == "Red Slime":
            self.strength = 7
            self.agility = 3
            self.HP = (4,4)
            self.sleep_resist = 0 / 16.0
            self.stopspell_resist = 15 / 16.0
            self.hurt_resist = 0 / 16.0
            self.dodge = 1 / 64.0
            self.E = 1
            self.G = (2, 2)
            self.run_resist = 0.25
            self.pattern = [("Attack", 1)]
            self.image = pygame.image.load("images/enemies/red_slime.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/red_slime_shadow.png").convert()
        elif name == "Drakee":
            self.strength = 9
            self.agility = 6
            self.HP = (5,6)
            self.sleep_resist = 0 / 16.0
            self.stopspell_resist = 15 / 16.0
            self.hurt_resist = 0 / 16.0
            self.dodge = 1 / 64.0
            self.E = 2
            self.G = (2, 2)
            self.run_resist = 0.25
            self.pattern = [("Attack", 1)]
            self.image = pygame.image.load("images/enemies/drakee.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/drakee_shadow.png").convert()
        elif name == "Ghost":
            self.strength = 11
            self.agility = 8
            self.HP = (6,7)
            self.maxhp = self.HP
            self.sleep_resist = 0 / 16.0
            self.stopspell_resist = 15 / 16.0
            self.hurt_resist = 0 / 16.0
            self.dodge = 4 / 64.0
            self.E = 3
            self.G = (3,4)
            self.run_resist = 0.25
            self.pattern = [("Attack", 1)]
            self.image = pygame.image.load("images/enemies/ghost.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/ghost_shadow.png").convert()
        elif name == "Magician":
            self.strength = 11
            self.agility = 12
            self.HP = (10,13)
            self.maxhp = self.HP
            self.sleep_resist = 0 / 16.0
            self.stopspell_resist = 0 / 16.0
            self.hurt_resist = 0 / 16.0
            self.dodge = 1 / 64.0
            self.E = 4
            self.G = (9,11)
            self.run_resist = 0.25
            self.pattern = [("HURT", 0.50), ("Attack", 1)]
            self.image = pygame.image.load("images/enemies/magician.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/magician_shadow.png").convert()
        elif name == "Magidrakee":
            self.strength = 14
            self.agility = 14
            self.HP = (12,15)
            self.maxhp = self.HP
            self.sleep_resist = 0 / 16.0
            self.stopspell_resist = 0 / 16.0
            self.hurt_resist = 0 / 16.0
            self.dodge = 1 / 64.0
            self.E = 5
            self.G = (9,11)
            self.run_resist = 0.25
            self.pattern = [("HURT", 0.50), ("Attack", 1)]
            self.image = pygame.image.load("images/enemies/magi_drakee.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/magi_drakee_shadow.png").convert()
        elif name == "Scorpion":
            self.strength = 18
            self.agility = 16
            self.HP = (16,20)
            self.maxhp = self.HP
            self.sleep_resist = 0 / 16.0
            self.stopspell_resist = 15 / 16.0
            self.hurt_resist = 0 / 16.0
            self.dodge = 1 / 64.0
            self.E = 6
            self.G = (12,15)
            self.run_resist = 0.25
            self.pattern = [("Attack", 1)]
            self.image = pygame.image.load("images/enemies/scorpion.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/scorpion_shadow.png").convert()
        elif name == "Druin":
            self.strength = 20
            self.agility = 18
            self.HP = (17,22)
            self.maxhp = self.HP
            self.sleep_resist = 0 / 16.0
            self.stopspell_resist = 15 / 16.0
            self.hurt_resist = 0 / 16.0
            self.dodge = 2 / 64.0
            self.E = 7
            self.G = (12,15)
            self.run_resist = 0.25
            self.pattern = [("Attack", 1)]
            self.image = pygame.image.load("images/enemies/druin.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/druin_shadow.png").convert()
        elif name == "Poltergeist":
            self.strength = 18
            self.agility = 20
            self.HP = (18,23)
            self.maxhp = self.HP
            self.sleep_resist = 0 / 16.0
            self.stopspell_resist = 0 / 16.0
            self.hurt_resist = 0 / 16.0
            self.dodge = 6 / 64.0
            self.E = 8
            self.G = (13,17)
            self.run_resist = 0.25
            self.pattern = [("HEAL", 0.70, "HP<25%"), ("HURT", 0.50), ("Attack", 1)]
            self.image = pygame.image.load("images/enemies/poltergeist.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/poltergeist_shadow.png").convert()
        elif name == "Droll":
            self.strength = 24
            self.agility = 24
            self.HP = (19,25)
            self.maxhp = self.HP
            self.sleep_resist = 0 / 16.0
            self.stopspell_resist = 14 / 16.0
            self.hurt_resist = 0 / 16.0
            self.dodge = 2 / 64.0
            self.E = 10
            self.G = (18,24)
            self.run_resist = 0.25
            self.pattern = [("Attack", 1)]
            self.image = pygame.image.load("images/enemies/droll.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/droll_shadow.png").convert()
        elif name == "Drakeema":
            self.strength = 22
            self.agility = 26
            self.HP = (16,20)
            self.maxhp = self.HP
            self.sleep_resist = 2 / 16.0
            self.stopspell_resist = 0 / 16.0
            self.hurt_resist = 0 / 16.0
            self.dodge = 6 / 64.0
            self.E = 11
            self.G = (15,19)
            self.run_resist = 0.25
            self.pattern = [("HEAL", 0.25, "HP<25%"), ("HURT", 0.50), ("Attack", 1)]
            self.pattern_hint = "Heal only if < 25% HP"
            self.image = pygame.image.load("images/enemies/drakeema.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/drakeema_shadow.png").convert()
        elif name == "Skeleton":
            self.strength = 28
            self.agility = 22
            self.HP = (23,30)
            self.maxhp = self.HP
            self.sleep_resist = 0 / 16.0
            self.stopspell_resist = 15 / 16.0
            self.hurt_resist = 0 / 16.0
            self.dodge = 4 / 64.0
            self.E = 11
            self.G = (22,29)
            self.run_resist = 0.25
            self.pattern = [("Attack", 1)]
            self.image = pygame.image.load("images/enemies/skeleton.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/skeleton_shadow.png").convert()
        elif name == "Warlock":
            self.strength = 28
            self.agility = 22
            self.HP = (23,30)
            self.maxhp = self.HP
            self.sleep_resist = 3 / 16.0
            self.stopspell_resist = 1 / 16.0
            self.hurt_resist = 0 / 16.0
            self.dodge = 2 / 64.0
            self.E = 13
            self.G = (26,34)
            self.run_resist = 0.25
            self.pattern = [("SLEEP", 0.25, "RequireAwake"), ("HURT", 0.50), ("Attack", 1)]
            self.image = pygame.image.load("images/enemies/warlock.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/warlock_shadow.png").convert()
        elif name == "Metal Scorpion":
            self.strength = 36
            self.agility = 42
            self.HP = (17,22)
            self.maxhp = self.HP
            self.sleep_resist = 0 / 16.0
            self.stopspell_resist = 15 / 16.0
            self.hurt_resist = 0 / 16.0
            self.dodge = 2 / 64.0
            self.E = 14
            self.G = (30,39)
            self.run_resist = 0.25
            self.pattern = [("Attack", 1)]
            self.image = pygame.image.load("images/enemies/metal_scorpion.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/metal_scorpion_shadow.png").convert()
        elif name == "Wolf":
            self.strength = 40
            self.agility = 30
            self.HP = (26,34)
            self.maxhp = self.HP
            self.sleep_resist = 1 / 16.0
            self.stopspell_resist = 15 / 16.0
            self.hurt_resist = 0 / 16.0
            self.dodge = 2 / 64.0
            self.E = 16
            self.G = (37,49)
            self.run_resist = 0.25
            self.pattern = [("Attack", 1)]
            self.image = pygame.image.load("images/enemies/wolf.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/wolf_shadow.png").convert()
        elif name == "Wraith":
            self.strength = 44
            self.agility = 34
            self.HP = (28,36)
            self.maxhp = self.HP
            self.sleep_resist = 7 / 16.0
            self.stopspell_resist = 0 / 16.0
            self.hurt_resist = 0 / 16.0
            self.dodge = 4 / 64.0
            self.E = 17
            self.G = (45,59)
            self.run_resist = 0.25
            self.pattern = [("HEAL", 0.25, "HP<25%"), ("Attack", 1)]
            self.image = pygame.image.load("images/enemies/wraith.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/wraith_shadow.png").convert()
        elif name == "Metal Slime":
            self.strength = 10
            self.agility = 255
            self.HP = (4, 4)
            self.maxhp = self.HP
            self.sleep_resist = 15 / 16.0
            self.stopspell_resist = 15 / 16.0
            self.hurt_resist = 15 / 16.0
            self.dodge = 1 / 64.0
            self.E = 115
            self.G = (4,5)
            self.run_resist = 0.25
            self.pattern = [("HURT", 0.75), ("Attack", 1)]
            self.image = pygame.image.load("images/enemies/metal_slime.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/metal_slime_shadow.png").convert()
        elif name == "Specter":
            self.strength = 40
            self.agility = 38
            self.HP = (28,36)
            self.maxhp = self.HP
            self.sleep_resist = 3 / 16.0
            self.stopspell_resist = 1 / 16.0
            self.hurt_resist = 0 / 16.0
            self.dodge = 4 / 64.0
            self.E = 18
            self.G = (52,69)
            self.run_resist = 0.25
            self.pattern = [("SLEEP", 0.50, "RequireAwake"), ("HURT", 0.75), ("Attack", 1)]
            self.pattern_hint = "Sleep only if hero not asleep"
            self.image = pygame.image.load("images/enemies/specter.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/specter_shadow.png").convert()
        elif name == "Wolflord":
            self.strength = 50
            self.agility = 36
            self.HP = (29,38)
            self.maxhp = self.HP
            self.sleep_resist = 4 / 16.0
            self.stopspell_resist = 7 / 16.0
            self.hurt_resist = 0 / 16.0
            self.dodge = 2 / 64.0
            self.E = 20
            self.G = (60,79)
            self.run_resist = 0.25
            self.pattern = [("STOPSPELL", 0.50, "RequireSpell"), ("Attack", 1)]
            self.pattern_hint = "Stopspell only if hero not stopspelled"
            self.image = pygame.image.load("images/enemies/wolflord.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/wolflord_shadow.png").convert()
        elif name == "Druinlord":
            self.strength = 47
            self.agility = 40
            self.HP = (27,35)
            self.maxhp = self.HP
            self.sleep_resist = 15 / 16.0
            self.stopspell_resist = 0 / 16.0
            self.hurt_resist = 0 / 16.0
            self.dodge = 4 / 64.0
            self.E = 20
            self.G = (63,84)
            self.run_resist = 0.25
            self.pattern = [("HEAL", 0.75, "HP<25%"), ("HURT", 0.25), ("Attack", 1)]
            self.pattern_hint = "75% chance to Heal only if < 25% HP"
            self.image = pygame.image.load("images/enemies/druinlord.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/druinlord_shadow.png").convert()
        elif name == "Drollmagi":
            self.strength = 52
            self.agility = 50
            self.HP = (29,38)
            self.maxhp = self.HP
            self.sleep_resist = 2 / 16.0
            self.stopspell_resist = 2 / 16.0
            self.hurt_resist = 0 / 16.0
            self.dodge = 1 / 64.0
            self.E = 22
            self.G = (67,89)
            self.run_resist = 0.375
            self.pattern = [("STOPSPELL", 0.50, "RequireSpell"), ("Attack", 1)]
            self.pattern_hint = "Stopspell only if hero not stopspelled"
            self.image = pygame.image.load("images/enemies/drollmagi.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/drollmagi_shadow.png").convert()
        elif name == "Wyvern":
            self.strength = 56
            self.agility = 48
            self.HP = (32,42)
            self.maxhp = self.HP
            self.sleep_resist = 4 / 16.0
            self.stopspell_resist = 15 / 16.0
            self.hurt_resist = 0 / 16.0
            self.dodge = 2 / 64.0
            self.E = 24
            self.G = (75,99)
            self.run_resist = 0.375
            self.pattern = [("Attack", 1)]
            self.image = pygame.image.load("images/enemies/wyvern.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/wyvern_shadow.png").convert()
        elif name == "Rogue Scorpion":
            self.strength = 60
            self.agility = 90
            self.HP = (27,35)
            self.maxhp = self.HP
            self.sleep_resist = 7 / 16.0
            self.stopspell_resist = 15 / 16.0
            self.hurt_resist = 0 / 16.0
            self.dodge = 2 / 64.0
            self.E = 26
            self.G = (82,109)
            self.run_resist = 0.375
            self.pattern = [("Attack", 1)]
            self.image = pygame.image.load("images/enemies/rogue_scorpion.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/rogue_scorpion_shadow.png").convert()
        elif name == "Wraith Knight":
            self.strength = 68
            self.agility = 56
            self.HP = (35,46)
            self.maxhp = self.HP
            self.sleep_resist = 5 / 16.0
            self.stopspell_resist = 0 / 16.0
            self.hurt_resist = 3 / 16.0
            self.dodge = 4 / 64.0
            self.E = 28
            self.G = (90,119)
            self.run_resist = 0.375
            self.pattern = [("HEAL", 0.75, "HP<25%"), ("Attack", 1)]
            self.pattern_hint = "75% chance to Heal only if < 25% HP"
            self.image = pygame.image.load("images/enemies/wraith_knight.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/wraith_knight_shadow.png").convert()
        elif name == "Golem":
            self.strength = 120
            self.agility = 60
            self.HP = (53,70)
            self.maxhp = self.HP
            self.sleep_resist = 15 / 16.0
            self.stopspell_resist = 15 / 16.0
            self.hurt_resist = 15 / 16.0
            self.dodge = 0 / 64.0
            self.E = 5
            self.G = (7,9)
            self.run_resist = 0.375
            self.pattern = [("Attack", 1)]
            self.image = pygame.image.load("images/enemies/golem.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/golem_shadow.png").convert()
        elif name == "Goldman":
            self.strength = 48
            self.agility = 40
            self.HP = (38,50)
            self.maxhp = self.HP
            self.sleep_resist = 13 / 16.0
            self.stopspell_resist = 15 / 16.0
            self.hurt_resist = 0 / 16.0
            self.dodge = 1 / 64.0
            self.E = 6
            self.G = (150,199)
            self.run_resist = 0.375
            self.pattern = [("Attack", 1)]
            self.image = pygame.image.load("images/enemies/goldman.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/goldman_shadow.png").convert()
        elif name == "Knight":
            self.strength = 76
            self.agility = 78
            self.HP = (42,55)
            self.maxhp = self.HP
            self.sleep_resist = 6 / 16.0
            self.stopspell_resist = 7 / 16.0
            self.hurt_resist = 0 / 16.0
            self.dodge = 1 / 64.0
            self.E = 33
            self.G = (97,129)
            self.run_resist = 0.375
            self.pattern = [("STOPSPELL", 0.50, "RequireSpell"), ("Attack", 1)]
            self.pattern_hint = "50% chance to Stopspell only if hero not stopspelled"
            self.image = pygame.image.load("images/enemies/knight.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/knight_shadow.png").convert()
        elif name == "Magiwyvern":
            self.strength = 78
            self.agility = 68
            self.HP = (44,58)
            self.maxhp = self.HP
            self.sleep_resist = 2 / 16.0
            self.stopspell_resist = 0 / 16.0
            self.hurt_resist = 0 / 16.0
            self.dodge = 2 / 64.0
            self.E = 34
            self.G = (105,139)
            self.run_resist = 0.375
            self.pattern = [("SLEEP", 0.50, "RequireAwake"), ("Attack", 1)]
            self.pattern_hint = "50% chance to Sleep only if hero not asleep"
            self.image = pygame.image.load("images/enemies/magi_wyvern.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/magi_wyvern_shadow.png").convert()
        elif name == "Demon Knight":
            self.strength = 79
            self.agility = 64
            self.HP = (38,50)
            self.maxhp = self.HP
            self.sleep_resist = 15 / 16.0
            self.stopspell_resist = 15 / 16.0
            self.hurt_resist = 15 / 16.0
            self.dodge = 15 / 64.0
            self.E = 37
            self.G = (112,149)
            self.run_resist = 0.375
            self.pattern = [("Attack", 1)]
            self.image = pygame.image.load("images/enemies/demon_knight.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/demon_knight_shadow.png").convert()
        elif name == "Werewolf":
            self.strength = 86
            self.agility = 70
            self.HP = (46,60)
            self.maxhp = self.HP
            self.sleep_resist = 7 / 16.0
            self.stopspell_resist = 15 / 16.0
            self.hurt_resist = 0 / 16.0
            self.dodge = 7 / 64.0
            self.E = 40
            self.G = (116,154)
            self.run_resist = 0.375
            self.pattern = [("Attack", 1)]
            self.image = pygame.image.load("images/enemies/werewolf.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/werewolf_shadow.png").convert()
        elif name == "Green Dragon":
            self.strength = 88
            self.agility = 74
            self.HP = (49,65)
            self.maxhp = self.HP
            self.sleep_resist = 7 / 16.0
            self.stopspell_resist = 15 / 16.0
            self.hurt_resist = 2 / 16.0
            self.dodge = 2 / 64.0
            self.E = 45
            self.G = (120,159)
            self.run_resist = 0.5
            self.pattern = [("FireBreath", 0.25), ("Attack", 1)]
            self.image = pygame.image.load("images/enemies/green_dragon.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/green_dragon_shadow.png").convert()
        elif name == "Starwyvern":
            self.strength = 86
            self.agility = 80
            self.HP = (49,65)
            self.maxhp = self.HP
            self.sleep_resist = 8 / 16.0
            self.stopspell_resist = 0 / 16.0
            self.hurt_resist = 1 / 16.0
            self.dodge = 2 / 64.0
            self.E = 45
            self.G = (120,159)
            self.run_resist = 0.5
            self.pattern = [("HEALMORE", 0.75, "HP<25%"), ("FireBreath", 0.25), ("Attack", 1)]
            self.pattern_hint = "75% chance to Healmore only if < 25% HP"
            self.image = pygame.image.load("images/enemies/star_wyvern.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/star_wyvern_shadow.png").convert()
        elif name == "Wizard":
            self.strength = 80
            self.agility = 70
            self.HP = (49,65)
            self.maxhp = self.HP
            self.sleep_resist = 15 / 16.0
            self.stopspell_resist = 7 / 16.0
            self.hurt_resist = 15 / 16.0
            self.dodge = 2 / 64.0
            self.E = 50
            self.G = (123,164)
            self.run_resist = 0.5
            self.pattern = [("HURTMORE", 0.50), ("Attack", 1)]
            self.image = pygame.image.load("images/enemies/wizard.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/wizard_shadow.png").convert()
        elif name == "Axe Knight":
            self.strength = 94
            self.agility = 82
            self.HP = (53,70)
            self.maxhp = self.HP
            self.sleep_resist = 15 / 16.0
            self.stopspell_resist = 3 / 16.0
            self.hurt_resist = 1 / 16.0
            self.dodge = 1 / 64.0
            self.E = 54
            self.G = (123,164)
            self.run_resist = 0.5
            self.pattern = [("SLEEP", 0.25, "RequireAwake"), ("Attack", 1)]
            self.pattern_hint = "25% chance to Sleep only if hero not asleep"
            self.image = pygame.image.load("images/enemies/axe_knight.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/axe_knight_shadow.png").convert()
        elif name == "Blue Dragon":
            self.strength = 98
            self.agility = 84
            self.HP = (53,70)
            self.maxhp = self.HP
            self.sleep_resist = 15 / 16.0
            self.stopspell_resist = 15 / 16.0
            self.hurt_resist = 7 / 16.0
            self.dodge = 2 / 64.0
            self.E = 60
            self.G = (112,149)
            self.pattern = [("FireBreath", 0.25), ("Attack", 1)]
            self.run_resist = 0.5
            self.image = pygame.image.load("images/enemies/blue_dragon.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/blue_dragon_shadow.png").convert()
        elif name == "Stoneman":
            self.strength = 100
            self.agility = 40
            self.HP = (121,160)
            self.maxhp = self.HP
            self.sleep_resist = 2 / 16.0
            self.stopspell_resist = 15 / 16.0
            self.hurt_resist = 7 / 16.0
            self.dodge = 1 / 64.0
            self.E = 65
            self.G = (105,139)
            self.pattern = [("Attack", 1)]
            self.run_resist = 1.0
            self.image = pygame.image.load("images/enemies/stoneman.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/stoneman_shadow.png").convert()
        elif name == "Armored Knight":
            self.strength = 105
            self.agility = 86
            self.HP = (68,90)
            self.maxhp = self.HP
            self.sleep_resist = 15 / 16.0
            self.stopspell_resist = 7 / 16.0
            self.hurt_resist = 1 / 16.0
            self.dodge = 2 / 64.0
            self.E = 70
            self.G = (105,139)
            self.run_resist = 1.0
            self.pattern = [("HEALMORE", 0.75, "HP<25%"), ("HURTMORE", 0.25), ("Attack", 1)]
            self.pattern_hint = "75% chance to Healmore only if < 25% HP"
            self.image = pygame.image.load("images/enemies/armored_knight.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/armored_knight_shadow.png").convert()
        elif name == "Red Dragon":
            self.strength = 120
            self.agility = 90
            self.HP = (76,100)
            self.maxhp = self.HP
            self.sleep_resist = 15 / 16.0
            self.stopspell_resist = 7 / 16.0
            self.hurt_resist = 15 / 16.0
            self.dodge = 2 / 64.0
            self.E = 100
            self.G = (105,139)
            self.run_resist = 1.0
            self.pattern = [("SLEEP", 0.25, "RequireAwake"), ("FireBreath", 0.25), ("Attack", 1)]
            self.pattern_hint = "25% chance to Sleep only if hero not asleep"
            self.image = pygame.image.load("images/enemies/red_dragon.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/red_dragon_shadow.png").convert()
        elif name == "Dragonlord first form":
            self.name = "Dragonlord"
            self._dl = 1  # dragonlord type 1
            self.strength = 90
            self.agility = 75
            self.HP = (76,100)
            self.maxhp = self.HP
            self.sleep_resist = 15 / 16.0
            self.stopspell_resist = 15 / 16.0
            self.hurt_resist = 15 / 16.0
            self.dodge = 0 / 64.0
            self.E = 0
            self.G = (0,0)
            self.run_resist = 1.0
            self.pattern = [("STOPSPELL", 0.25, "RequireSpell"), ("HURTMORE", 0.75), ("Attack", 1)]
            self.pattern_hint = "25% chance to Stopspell only if hero not stopspelled"
            self.image = pygame.image.load("images/enemies/human_dragonlord.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/human_dragonlord_shadow.png").convert()
        elif name == "Dragonlord second form":
            self.name = "Dragonlord"
            self._dl = 2 #dragonlord type 2
            self.strength = 140
            self.agility = 200
            self.HP = (130,130)
            self.maxhp = self.HP
            self.sleep_resist = 15 / 16.0
            self.stopspell_resist = 15 / 16.0
            self.hurt_resist = 15 / 16.0
            self.dodge = 0 / 64.0
            self.E = 0
            self.G = (0,0)
            self.run_resist = 1.0
            self.pattern = [("StrongFireBreath", 0.50), ("Attack", 1)]
            self.image = pygame.image.load("images/enemies/true_dragonlord.png").convert()
            self.red_shadow = pygame.image.load("images/enemies/true_dragonlord_shadow.png").convert()

        self.HP = random.randint(self.HP[0], self.HP[1])
        self.maxhp = self.HP
        self.spell_stopped = False
        self.asleep = False
        self.turns_asleep = 0